name: NetherRatio
version: '${version}'
main: ro.cofi.netherratio.NetherRatio
api-version: 1.19
authors: [ Deathcofi ]
description: A PaperMC plugin to allow customizable Nether to Overworld ratio.
commands:
    nrreload:
        aliases: [nrrel]
        description: Reload the configuration files (admin command).
        usage: "Usage: /<command>"
        permission: netherratio.nrreload
permissions:
    netherratio.nrreload:
        description: Permission to run the /nrreload command. Administrative command.
    netherratio.*:
        description: Wildcard permission for any NetherRatio command.
        children:
            netherratio.nrreload: true